version: "3.9"
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
    restart: always
  backend:
    depends_on:
      database:
        condition: service_started
    links:
      - db
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_USER: root
      DB_PASSWORD: secret
      DB_URL: database:3306/homestead
    ports:
      - "9000:9000"